version: "3.5"

services:
  app:
    build: .
    command: ./scripts/start.sh
    ports:
      - 2048:2048
    volumes:
      - .:/app
      - /opt/rubygems:/bundle_path
    env_file:
      - .env

  database:
    image: mysql
    volumes:
        - /data/mysql:/var/lib/mysql
    env_file:
      - .env


    


