version: "3.5"

services:
  app:
    build: .
    command: ./scripts/start.sh
    ports:
      - 2048:2048
    volumes:
      - .:/app
      - /opt/rubygems:/bundle_path

  database:
    image: mysql
    volumes:
        - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pass234fsword
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

    


